name = gadgets_tweaks
description = Strips Technic dependencies from gadgets_modpack and enforces standard mechanical wear.
depends = gadgets_api
optional_depends = gadgets_magic, gadgets_consumables
