name = dungeon_tweaks
description = Overhauls dungeon and open-world loot pools, adds tiered loot rotation, and places raider defenders in dungeons.
optional_depends = dungeonsplus, lootchests, lootchests_default, raiders, default, farming, magic_materials, 3d_armor, shields, ropes, bones, binoculars, vessels, tnt, stairs, bonemeal, cheese, wine, bucket, flowers, airtanks, map, dye
