name = evergrowth
title       = Evergrowth
description = A unique survival and exploration experience built on custom modules and progressive expansion.
min_minetest_version = 5.8
release = 1
author = Aresh
