name = i_have_hands_tweaks
description = Space vacuum compatibility, nil-safety, and altitude fix for i_have_hands carrying system.
depends = i_have_hands
optional_depends = vacuum, drawers, pipeworks, mcl_armor_stand, mcl_armor
