release = 16438
author = mt-mods
description = A modpack providing full progression of magic and technology-based items that apply status effects or do other useful functions
name = gadgets_modpack
title = Gadgets Modpack
