name = hidroplane
depends = airutils,supercub, mobkit, default, biofuel
optional_depends = biofuel, climate_api
author = apercy
description = Adds a craftable hydroplane
title = Super Duck Hydroplane
