name = techage_tweaks
description = Extracts custom techage logic into an override mod (oil scanner, auto-stringing, liquid support, lamp junctions)
depends = techage
optional_depends = autobahn, motorboat, airutils
