release = 16441
author = mt-mods
description = A weapons modpack aiming at providing a complete, technologic and magic progression of ranged weapons, along with an API to easily make your own ones.
name = bweapons_modpack
title = bweapons modpack
