#!/usr/bin/env python3
"""Generate OBJ mesh models for eg_settlers job blocks."""

import os

MODEL_DIR = "/Users/Aresh/Desktop/Projects/evergrowth/mods/eg_settlers/models"


def generate_obj(filename, parts):
    lines = []
    lines.append("# Generated by generate_job_block_models.py")

    vertex_index = 1
    all_groups = []

    for mat_name, boxes in parts:
        faces_for_mat = []
        for box in boxes:
            x1, y1, z1, x2, y2, z2 = box
            lines.append(f"v {x1} {y1} {z1}")
            lines.append(f"v {x2} {y1} {z1}")
            lines.append(f"v {x2} {y2} {z1}")
            lines.append(f"v {x1} {y2} {z1}")
            lines.append(f"v {x1} {y1} {z2}")
            lines.append(f"v {x2} {y1} {z2}")
            lines.append(f"v {x2} {y2} {z2}")
            lines.append(f"v {x1} {y2} {z2}")

            vi = vertex_index
            faces_for_mat.extend([
                (vi+0, vi+1, vi+2, vi+3),
                (vi+5, vi+4, vi+7, vi+6),
                (vi+4, vi+0, vi+3, vi+7),
                (vi+1, vi+5, vi+6, vi+2),
                (vi+3, vi+2, vi+6, vi+7),
                (vi+4, vi+5, vi+1, vi+0),
            ])
            vertex_index += 8
        all_groups.append((mat_name, faces_for_mat))

    lines.append("vt 0 1")
    lines.append("vt 1 1")
    lines.append("vt 1 0")
    lines.append("vt 0 0")

    for mat_name, faces in all_groups:
        lines.append("")
        lines.append(f"usemtl {mat_name}")
        lines.append(f"g {mat_name.lower()}_group")
        for a, b, c, d in faces:
            lines.append(f"f {a}/1 {b}/2 {c}/3 {d}/4")

    lines.append("")

    filepath = os.path.join(MODEL_DIR, filename)
    with open(filepath, "w") as f:
        f.write("\n".join(lines))
    total_verts = (vertex_index - 1)
    total_faces = sum(len(g[1]) for g in all_groups)
    print(f"  {filename}: {total_verts} verts, {total_faces} faces")


MODELS = {
    # 1. FARMER'S SEED SILO — tall 1.7-block wooden silo tower with roof cap & metal hoops
    "eg_settlers_job_farmer.obj": [
        ("Mat1_Wood", [
            (-0.4,  -0.5, -0.4,   0.4,  -0.35,  0.4),    # base rim
            (-0.35, -0.35,-0.35,  0.35,  0.9,   0.35),   # main silo tower body (1.25m tall)
        ]),
        ("Mat2_Grain", [
            (-0.4,   0.9, -0.4,   0.4,   1.05,  0.4),    # overhang roof rim
            (-0.3,   1.05,-0.3,   0.3,   1.15,  0.3),    # roof middle cone
            (-0.15,  1.15,-0.15,  0.15,  1.2,   0.15),   # roof top cap
            (-0.1,  -0.15,-0.45,  0.1,   0.05, -0.35),   # grain output chute front
        ]),
    ],

    # 2. BLACKSMITH'S QUENCHING TROUGH — stone basin with water fill
    "eg_settlers_job_smith.obj": [
        ("Mat1_Stone", [
            (-0.5, -0.5, -0.4,   0.5,  -0.2,  0.4),     # floor slab
            (-0.5, -0.2, -0.4,   0.5,   0.15, -0.25),    # front wall
            (-0.5, -0.2,  0.25,  0.5,   0.15,  0.4),     # back wall
            (-0.5, -0.2, -0.25, -0.35,  0.15,  0.25),    # left wall
            ( 0.35,-0.2, -0.25,  0.5,   0.15,  0.25),    # right wall
        ]),
        ("Mat2_Water", [
            (-0.35, 0.0, -0.25,  0.35,  0.05,  0.25),   # water surface
        ]),
    ],

    # 3. CARPENTER'S DRAFTING TABLE — four-legged desk with angled drafting top
    "eg_settlers_job_carpenter.obj": [
        ("Mat1_Wood", [
            (-0.45,-0.5, -0.4,  -0.35,  0.2,  -0.3),    # leg FL
            ( 0.35,-0.5, -0.4,   0.45,  0.2,  -0.3),    # leg FR
            (-0.45,-0.5,  0.3,  -0.35,  0.2,   0.4),    # leg BL
            ( 0.35,-0.5,  0.3,   0.45,  0.2,   0.4),    # leg BR
            (-0.5,  0.2, -0.45,  0.5,   0.32,  0.45),   # table top slab
            (-0.4, -0.15,-0.35,  0.4,  -0.05,  0.35),   # shelf crossbar
        ]),
        ("Mat2_Paper", [
            (-0.35, 0.32,-0.3,   0.35,  0.35,  0.3),    # blueprint paper roll
        ]),
    ],

    # 4. LIBRARIAN'S ARCHIVE CABINET — tall 1.5-block bookcase cabinet
    "eg_settlers_job_librarian.obj": [
        ("Mat1_Wood", [
            (-0.45,-0.5, -0.35,  0.45, -0.4,   0.35),   # base plinth
            (-0.4, -0.4, -0.3,   0.4,   0.9,   0.3),    # cabinet carcass (1.3m tall)
            (-0.45, 0.9, -0.35,  0.45,  1.0,   0.35),   # crown molding
        ]),
        ("Mat2_Books", [
            (-0.35,-0.3, -0.32,  0.35,  0.1,  -0.28),   # lower shelf books
            (-0.35, 0.2, -0.32,  0.35,  0.8,  -0.28),   # upper shelf books
        ]),
    ],

    # 5. MAGE'S WARD PEDESTAL — tall 1.4-block obsidian obelisk pedestal
    "eg_settlers_job_mage.obj": [
        ("Mat1_Obsidian", [
            (-0.45,-0.5, -0.45,  0.45, -0.3,   0.45),   # wide base step
            (-0.3, -0.3, -0.3,   0.3,   0.3,   0.3),    # column stem
            (-0.4,  0.3, -0.4,   0.4,   0.45,  0.4),    # top altar plate
        ]),
        ("Mat2_Crystal", [
            (-0.15, 0.45,-0.15,  0.15,  0.85,  0.15),   # floating Mese crystal orb
        ]),
    ],

    # 6. BREWER'S FERMENTATION CASK — barrel on wooden legs with steel tap
    "eg_settlers_job_brewer.obj": [
        ("Mat1_Wood", [
            (-0.45,-0.5, -0.4,  -0.35, -0.05, -0.3),    # leg FL
            ( 0.35,-0.5, -0.4,   0.45, -0.05, -0.3),    # leg FR
            (-0.45,-0.5,  0.3,  -0.35, -0.05,  0.4),    # leg BL
            ( 0.35,-0.5,  0.3,   0.45, -0.05,  0.4),    # leg BR
            (-0.45,-0.15,-0.4,   0.45, -0.05, -0.3),    # crossbar F
            (-0.45,-0.15, 0.3,   0.45, -0.05,  0.4),    # crossbar B
            (-0.4, -0.05,-0.45,  0.4,   0.55,  0.45),   # barrel belly
        ]),
        ("Mat2_Steel", [
            (-0.42,-0.05,-0.48,  0.42,  0.57, -0.45),   # steel hoop F
            (-0.42,-0.05, 0.45,  0.42,  0.57,  0.48),   # steel hoop B
            (-0.05, 0.15,-0.55,  0.05,  0.28, -0.45),   # tap spigot
        ]),
    ],

    # 7. MINER'S ORE CART — minecart on wheels with ore fill
    "eg_settlers_job_miner.obj": [
        ("Mat1_Steel", [
            (-0.4, -0.2, -0.35,  0.4,  -0.1,   0.35),   # chassis
            (-0.45,-0.1, -0.4,   0.45,  0.3,  -0.25),   # wall F
            (-0.45,-0.1,  0.25,  0.45,  0.3,   0.4),    # wall B
            (-0.45,-0.1, -0.25, -0.3,   0.3,   0.25),   # wall L
            ( 0.3, -0.1, -0.25,  0.45,  0.3,   0.25),   # wall R
            (-0.35,-0.5, -0.3,  -0.25, -0.2,  -0.2),    # wheel FL
            ( 0.25,-0.5, -0.3,   0.35, -0.2,  -0.2),    # wheel FR
            (-0.35,-0.5,  0.2,  -0.25, -0.2,   0.3),    # wheel BL
            ( 0.25,-0.5,  0.2,   0.35, -0.2,   0.3),    # wheel BR
        ]),
        ("Mat2_Ore", [
            (-0.3,  0.1, -0.2,   0.3,   0.35,  0.2),    # ore mound inside
        ]),
    ],

    # 8. MERCHANT'S COUNTER — shop counter with gold balance scale
    "eg_settlers_job_merchant.obj": [
        ("Mat1_Wood", [
            (-0.5, -0.5, -0.35,  0.5,   0.15,  0.35),   # counter base
            (-0.5,  0.15,-0.45,  0.5,   0.25,  0.45),   # counter top
        ]),
        ("Mat2_Gold", [
            (-0.15, 0.25,-0.15,  0.15,  0.35,  0.15),   # scale base
            (-0.3,  0.35,-0.05,  0.3,   0.38,  0.05),   # scale beam
            (-0.35, 0.3, -0.1,  -0.2,   0.35,  0.1),    # scale pan L
            ( 0.2,  0.3, -0.1,   0.35,  0.35,  0.1),    # scale pan R
        ]),
    ],

    # 9. GUARD'S WATCHTOWER BEACON — Concept A Armory Stand (Central Backboard & Non-Flickering Sword Hilt)
    "eg_settlers_job_guard.obj": [
        ("Mat1_Wood", [
            (-0.5, -0.5,  -0.4,   0.5,  -0.35,  0.4),    # full-width heavy wooden base slab
            (-0.45,-0.35, -0.06, -0.35,  0.85,  0.06),   # tall left timber post
            ( 0.35,-0.35, -0.06,  0.45,  0.85,  0.06),   # tall right timber post
            (-0.47, 0.85, -0.08, -0.33,  0.92,  0.08),   # left timber post cap
            ( 0.33, 0.85, -0.08,  0.47,  0.92,  0.08),   # right timber post cap
            (-0.35, 0.55, -0.05,  0.35,  0.65,  0.05),   # upper crossbar
            (-0.35,-0.05, -0.05,  0.35,  0.05,  0.05),   # lower crossbar
            (-0.15, 0.05, -0.05,  0.15,  0.55,  0.05),   # central wooden mounting backboard
        ]),
        ("Mat2_Steel", [
            # Tapered 3-tier spearhead tip (right post)
            ( 0.34, 1.10, -0.11,  0.42,  1.22, -0.03),   # spear socket base
            ( 0.36, 1.22, -0.10,  0.40,  1.34, -0.04),   # spear mid blade
            ( 0.37, 1.34, -0.09,  0.39,  1.44, -0.05),   # spear point tip

            # Sword assembly (left post - shifted forward along Z to Z = [-0.14, -0.08])
            (-0.37,-0.3,  -0.12, -0.33,  0.35, -0.08),   # steel sword blade
            (-0.43, 0.35, -0.14, -0.27,  0.40, -0.06),   # wide steel sword crossguard (no post intersection)
            (-0.39, 0.52, -0.12, -0.31,  0.58, -0.08),   # steel sword pommel cap

            # Shield border rim plate & MOUNTING BRACKETS ATTACHED TO CENTRAL BACKBOARD
            (-0.2,  0.0,  -0.22,  0.2,   0.6,  -0.16),   # outer shield steel border rim plate
            (-0.14, 0.25, -0.16, -0.08,  0.35, -0.05),   # left steel bracket mounted to backboard
            ( 0.08, 0.25, -0.16,  0.14,  0.35, -0.05),   # right steel bracket mounted to backboard
        ]),
        ("Mat3_Bronze", [
            (-0.16, 0.04, -0.26,  0.16,  0.56, -0.22),   # inner bronze shield face plate
            (-0.07, 0.22, -0.30,  0.07,  0.38, -0.26),   # raised bronze shield boss dome
        ]),
        ("Mat4_Handle", [
            ( 0.35,-0.35, -0.1,   0.41,  1.1,  -0.04),   # dark mahogany spear shaft
            (-0.38, 0.40, -0.12, -0.32,  0.52, -0.08),   # dark leather sword hilt grip
        ]),
    ],

    # 10. RANCHER'S FEED TROUGH — open wooden trough with hay fill
    "eg_settlers_job_rancher.obj": [
        ("Mat1_Wood", [
            (-0.5, -0.5, -0.3,   0.5,  -0.3,   0.3),    # trough floor
            (-0.5, -0.3, -0.3,   0.5,   0.15, -0.15),   # wall F
            (-0.5, -0.3,  0.15,  0.5,   0.15,  0.3),    # wall B
            (-0.5, -0.3, -0.15, -0.35,  0.15,  0.15),   # wall L
            ( 0.35,-0.3, -0.15,  0.5,   0.15,  0.15),   # wall R
            (-0.45,-0.5, -0.25, -0.35, -0.3,   0.25),   # leg L
            ( 0.35,-0.5, -0.25,  0.45, -0.3,   0.25),   # leg R
        ]),
        ("Mat2_Straw", [
            (-0.35,-0.1, -0.15,  0.35,  0.1,   0.15),   # hay fill
        ]),
    ],

    # 11. FISHER'S FISH BARREL — barrel with fish top
    "eg_settlers_job_fisher.obj": [
        ("Mat1_Wood", [
            (-0.35,-0.5, -0.35,  0.35,  0.35,  0.35),   # barrel body
            (-0.38,-0.5, -0.38,  0.38, -0.45,  0.38),   # base ring
        ]),
        ("Mat2_Steel", [
            (-0.38, 0.2, -0.38,  0.38,  0.28,  0.38),   # upper hoop
            (-0.38,-0.3, -0.38,  0.38, -0.22,  0.38),   # lower hoop
            (-0.3,  0.35,-0.3,   0.3,   0.42,  0.3),    # fish/water top surface
        ]),
    ],

    # 12. LUMBERJACK'S CHOPPING STUMP — tree stump with sticks and slender axe
    "eg_settlers_job_lumberjack.obj": [
        ("Mat1_Bark", [
            (-0.45,-0.5, -0.45,  0.45,  0.15,  0.45),   # log stump bark body
            (-0.35, 0.2, -0.3,  -0.15,  0.28, -0.22),   # wooden stick 1 bark (left)
            ( 0.12, 0.2,  0.1,   0.38,  0.28,  0.18),   # wooden stick 2 bark (right)
            (-0.25, 0.2,  0.22,  0.15,  0.28,  0.3),    # wooden stick 3 bark (back)
        ]),
        ("Mat2_Top", [
            (-0.45, 0.15,-0.45,  0.45,  0.2,   0.45),   # log top ring face
            (-0.37, 0.2, -0.3,  -0.13,  0.28, -0.22),   # stick 1 end cuts
            ( 0.1,  0.2,  0.1,   0.4,   0.28,  0.18),   # stick 2 end cuts
            (-0.27, 0.2,  0.22,  0.17,  0.28,  0.3),    # stick 3 end cuts
        ]),
        ("Mat3_Steel", [
            (-0.03, 0.18,-0.18,  0.03,  0.42,  0.02),   # slender steel axe head blade
        ]),
        ("Mat4_Handle", [
            (-0.02, 0.25, 0.0,   0.02,  0.72,  0.06),   # slender vertical axe handle shaft
        ]),
    ],

    # 13. TECHNOLOGIST'S SERVER RACK — 1.6-block steel rack cabinet
    "eg_settlers_job_technologist.obj": [
        ("Mat1_Steel", [
            (-0.4, -0.5, -0.35,  0.4,  -0.45,  0.35),   # base plinth
            (-0.35,-0.45,-0.3,   0.35,  1.05,  0.3),    # main rack body (1.5m tall)
            (-0.38, 1.05,-0.33,  0.38,  1.1,   0.33),   # top ventilation hood
        ]),
        ("Mat2_Lights", [
            (-0.3, -0.3, -0.33,  0.3,  -0.05, -0.3),    # server blade 1
            (-0.3,  0.1, -0.33,  0.3,   0.35, -0.3),    # server blade 2
            (-0.3,  0.5, -0.33,  0.3,   0.75, -0.3),    # server blade 3
            (-0.3,  0.85,-0.33,  0.3,   1.0,  -0.3),    # server blade 4
        ]),
    ],

    # 14. GUNSMITH'S ORDNANCE LOCKER — 1.5-block military steel locker
    "eg_settlers_job_gunsmith.obj": [
        ("Mat1_GreenSteel", [
            (-0.43,-0.5, -0.38,  0.43, -0.45,  0.38),   # base
            (-0.4, -0.45,-0.35,  0.4,   0.95,  0.35),   # locker body (1.4m tall)
            (-0.43, 0.95,-0.38,  0.43,  1.0,   0.38),   # top cap
        ]),
        ("Mat2_Door", [
            (-0.35,-0.4, -0.38, -0.05,  0.9,  -0.35),   # door L
            ( 0.05,-0.4, -0.38,  0.35,  0.9,  -0.35),   # door R
            (-0.08, 0.2, -0.41, -0.05,  0.35, -0.38),   # handle L
            ( 0.05, 0.2, -0.41,  0.08,  0.35, -0.38),   # handle R
        ]),
    ],

    # 15. AUTOMOBILE MECHANIC'S TOOL CHEST — rolling tool chest with drawers
    "eg_settlers_job_automobile_mechanic.obj": [
        ("Mat1_Red", [
            (-0.4, -0.35,-0.35,  0.4,   0.35,  0.35),   # main body
            (-0.35, 0.35,-0.3,   0.35,  0.5,   0.3),    # top lid section
        ]),
        ("Mat2_Steel", [
            (-0.35,-0.5, -0.3,  -0.25, -0.35, -0.2),    # wheel FL
            ( 0.25,-0.5, -0.3,   0.35, -0.35, -0.2),    # wheel FR
            (-0.35,-0.5,  0.2,  -0.25, -0.35,  0.3),    # wheel BL
            ( 0.25,-0.5,  0.2,   0.35, -0.35,  0.3),    # wheel BR
            (-0.3,  0.5, -0.05,  0.3,   0.55,  0.05),   # top handle
            (-0.35,-0.1, -0.38,  0.35, -0.05, -0.35),   # drawer 1
            (-0.35, 0.15,-0.38,  0.35,  0.2,  -0.35),   # drawer 2
        ]),
    ],

    # 16. AIRCRAFT MECHANIC'S CANISTER RACK — fuel canister rack
    "eg_settlers_job_aircraft_mechanic.obj": [
        ("Mat1_Gold", [
            (-0.35,-0.3, -0.2,  -0.05,  0.4,   0.2),    # canister L
            ( 0.05,-0.3, -0.2,   0.35,  0.4,   0.2),    # canister R
        ]),
        ("Mat2_Frame", [
            (-0.45,-0.5, -0.35,  0.45, -0.3,   0.35),   # base tray
            (-0.4,  0.4, -0.05,  0.4,   0.5,   0.05),   # top bar
            (-0.4, -0.3, -0.05, -0.35,  0.4,   0.05),   # upright L
            ( 0.35,-0.3, -0.05,  0.4,   0.4,   0.05),   # upright R
        ]),
    ],

    # 17. NAUTICAL MECHANIC'S CHAIN POST — dock bollard post
    "eg_settlers_job_nautical_mechanic.obj": [
        ("Mat1_Blue", [
            (-0.2, -0.1, -0.2,   0.2,   0.35,  0.2),    # bollard post
            (-0.25, 0.35,-0.25,  0.25,  0.45,  0.25),   # post cap
            (-0.35, 0.1, -0.05,  0.35,  0.2,   0.05),   # chain crossbar
        ]),
        ("Mat2_Stone", [
            (-0.45,-0.5, -0.45,  0.45, -0.1,   0.45),   # stone pier base
        ]),
    ],

    # 18. ROBOTICIST'S CHARGING ALCOVE — 1.7-block copper & steel archway
    "eg_settlers_job_roboticist.obj": [
        ("Mat1_Steel", [
            (-0.45,-0.5, -0.4,  -0.3,   1.1,   0.4),    # left arch pillar (1.6m tall)
            ( 0.3, -0.5, -0.4,   0.45,  1.1,   0.4),    # right arch pillar
            (-0.3,  0.9, -0.4,   0.3,   1.2,   0.4),    # top canopy beam (1.7m top)
            (-0.3, -0.5,  0.25,  0.3,   0.9,   0.4),    # rear backboard
        ]),
        ("Mat2_Charge", [
            (-0.3, -0.5, -0.35,  0.3,  -0.4,   0.25),   # floor charging pad
            (-0.2,  0.2, -0.43,  0.2,   0.5,  -0.4),    # glowing power core screen
        ]),
    ],
}


if __name__ == "__main__":
    os.makedirs(MODEL_DIR, exist_ok=True)
    print("Generating Job Block OBJ models...")
    for filename, parts in MODELS.items():
        generate_obj(filename, parts)
    print(f"Done - {len(MODELS)} models written to {MODEL_DIR}")
