name = eg_settlers
description = Simple village generation for Evergrowth
depends = default, ethereal, mobs_npc, stairs, farming, xdecor, wine
optional_depends = doc, guidebooks, airutils, supercub, pa28, hidroplane, heli, motorboat, nautilus, automobiles_pck, techage_modpack, maidroid_ng, biofuel, magic_materials, bweapons_api, bweapons_firearms_pack, bweapons_magic_pack, tnt, dye, wool
