name = eg_companions
description = Domestic companion NPCs dual-tethered to wallmounted Companion Plaques and player-owned beds.
depends = default, mobs, mobs_npc
optional_depends = beds, eg_settlers, 3d_armor
