name = lootchests_default
description = Part of lootchests_modpack, providing lootchests for minetest_game, as well as integration with some mods
depends = default, lootchests, tnt, vessels, screwdriver, map, fire, dye, wool, carts, bucket, boats, binoculars, farming, flowers
optional_depends = 3d_armor, shields, bonemeal, moreores, moretrees, gadgets_consumables
