name = maidroid
description = Cute droids working for you
optional_depends = better_farming, cucina_vegana, dye, entity_keys, ethereal, farming, pie
min_minetest_version = 5.3
supported_games = minetest_game
