name = other_worlds_tweaks
description = Evergrowth integration, rich ores, gravity monoids, and climate hooks for other_worlds.
depends = other_worlds, default
optional_depends = climate, climate_api, player_monoids, techage
