name = walls_tweaks
depends = walls
description = Modifies the visual appearance of walls to be smooth in straight lines, adding a post only when placed at corners, ends, or when supporting a block above.
