#!/usr/bin/env python3
"""Generate OBJ 3D mesh models for jumpdrive_tweaks bridge console and jump lever."""

import os
import math

MODEL_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)))


def generate_obj(filename, parts):
    lines = []
    lines.append("# Generated by generate_bridge_models.py for jumpdrive_tweaks")

    vertex_index = 1
    all_groups = []

    for mat_name, shapes in parts:
        faces_for_mat = []
        for shape in shapes:
            if len(shape) == 6:
                x1, y1, z1, x2, y2, z2 = shape
                lines.append(f"v {x1} {y1} {z1}")
                lines.append(f"v {x2} {y1} {z1}")
                lines.append(f"v {x2} {y2} {z1}")
                lines.append(f"v {x1} {y2} {z1}")
                lines.append(f"v {x1} {y1} {z2}")
                lines.append(f"v {x2} {y1} {z2}")
                lines.append(f"v {x2} {y2} {z2}")
                lines.append(f"v {x1} {y2} {z2}")

                vi = vertex_index
                faces_for_mat.extend([
                    (vi + 0, vi + 1, vi + 2, vi + 3), # North / Front (Z1)
                    (vi + 5, vi + 4, vi + 7, vi + 6), # South / Back (Z2)
                    (vi + 4, vi + 0, vi + 3, vi + 7), # West / Left (X1)
                    (vi + 1, vi + 5, vi + 6, vi + 2), # East / Right (X2)
                    (vi + 3, vi + 2, vi + 6, vi + 7), # Top (Y2)
                    (vi + 4, vi + 5, vi + 1, vi + 0), # Bottom (Y1)
                ])
                vertex_index += 8
            elif len(shape) == 7 and shape[0] == "cyl_x":
                # Cylinder aligned along X axis: ("cyl_x", x1, x2, cy, cz, r, segs)
                _, x1, x2, cy, cz, r, segs = shape
                lines.append(f"v {x1} {cy} {cz}")
                lines.append(f"v {x2} {cy} {cz}")
                vi_left_center = vertex_index
                vi_right_center = vertex_index + 1
                vertex_index += 2

                start_vi = vertex_index
                for i in range(segs):
                    angle = 2 * math.pi * i / segs
                    vy = cy + r * math.cos(angle)
                    vz = cz + r * math.sin(angle)
                    lines.append(f"v {x1} {vy} {vz}")
                    lines.append(f"v {x2} {vy} {vz}")
                    vertex_index += 2

                for i in range(segs):
                    l1 = start_vi + i * 2
                    r1 = start_vi + i * 2 + 1
                    l2 = start_vi + ((i + 1) % segs) * 2
                    r2 = start_vi + ((i + 1) % segs) * 2 + 1

                    # Tube face
                    faces_for_mat.append((l1, r1, r2, l2))
                    # Left cap
                    faces_for_mat.append((l2, l1, vi_left_center, vi_left_center))
                    # Right cap
                    faces_for_mat.append((r1, r2, vi_right_center, vi_right_center))

        all_groups.append((mat_name, faces_for_mat))

    lines.append("vt 0 1")
    lines.append("vt 1 1")
    lines.append("vt 1 0")
    lines.append("vt 0 0")

    for mat_name, faces in all_groups:
        lines.append("")
        lines.append(f"usemtl {mat_name}")
        lines.append(f"g {mat_name.lower()}_group")
        for a, b, c, d in faces:
            lines.append(f"f {a}/1 {b}/2 {c}/3 {d}/4")

    lines.append("")

    filepath = os.path.join(MODEL_DIR, filename)
    with open(filepath, "w") as f:
        f.write("\n".join(lines))
    total_verts = (vertex_index - 1)
    total_faces = sum(len(g[1]) for g in all_groups)
    print(f"Generated {filename}: {total_verts} verts, {total_faces} faces")


MODELS = {
    # 1. BRIDGE NAVIGATION CONSOLE
    # Material 1: Hull metal casing (default_steel_block or jumpdrive_bridge_console_side.png)
    # Material 2: Screen display (jumpdrive_bridge_console_top.png)
    # Material 3: Controls, keyboard, dial panels (jumpdrive_bridge_console_front.png)
    "jumpdrive_bridge_console.obj": [
        ("Mat1_Casing", [
            (-0.45, -0.50, -0.45,  0.45, -0.25,  0.45), # Base pedestal
            (-0.40, -0.25, -0.40,  0.40,  0.05,  0.40), # Main desk column
            (-0.48,  0.05, -0.45,  0.48,  0.15,  0.45), # Table desk slab
            (-0.44,  0.15,  0.10,  0.44,  0.48,  0.42), # Screen housing / back bezel
            (-0.48,  0.10, -0.46, -0.42,  0.22,  0.10), # Left armrest/guard
            ( 0.42,  0.10, -0.46,  0.48,  0.22,  0.10), # Right armrest/guard
        ]),
        ("Mat2_Screen", [
            (-0.38,  0.18,  0.15,  0.38,  0.45,  0.38), # Main flight radar & nav HUD display
        ]),
        ("Mat3_Controls", [
            (-0.40,  0.15, -0.40,  0.40,  0.17, -0.05), # Slanted keyboard & touch matrix
            (-0.40,  0.15, -0.05,  0.40,  0.19,  0.10), # Telemetry LED bar & throttle deck
        ]),
    ],

    # 2. TACTILE JUMP LEVER (DISENGAGED / UPRIGHT STATE)
    # Material 1: Base bracket and hinge axle
    # Material 2: Lever handle and warning grip
    "jumpdrive_jump_lever_off.obj": [
        ("Mat1_Bracket", [
            (-0.25, -0.35,  0.38,  0.25,  0.35,  0.50), # Backplate mounting surface
            (-0.16, -0.15,  0.15, -0.08,  0.15,  0.38), # Left hinge bracket
            ( 0.08, -0.15,  0.15,  0.16,  0.15,  0.38), # Right hinge bracket
            ("cyl_x", -0.16, 0.16, 0.0, 0.25, 0.04, 8), # Center pivot pin
        ]),
        ("Mat2_Lever", [
            (-0.05, -0.05,  0.18,  0.05,  0.38,  0.28), # Upright lever shaft
            (-0.08,  0.36,  0.14,  0.08,  0.48,  0.32), # Industrial grip head
        ]),
    ],

    # 3. TACTILE JUMP LEVER (ENGAGED / PULLED FORWARD STATE)
    "jumpdrive_jump_lever_on.obj": [
        ("Mat1_Bracket", [
            (-0.25, -0.35,  0.38,  0.25,  0.35,  0.50), # Backplate mounting surface
            (-0.16, -0.15,  0.15, -0.08,  0.15,  0.38), # Left hinge bracket
            ( 0.08, -0.15,  0.15,  0.16,  0.15,  0.38), # Right hinge bracket
            ("cyl_x", -0.16, 0.16, 0.0, 0.25, 0.04, 8), # Center pivot pin
        ]),
        ("Mat2_Lever", [
            (-0.05, -0.12, -0.05,  0.05,  0.06,  0.24), # Forward angled lever shaft
            (-0.08, -0.22, -0.18,  0.08, -0.06, -0.02), # Pulled forward grip head
        ]),
    ],
}


def main():
    os.makedirs(MODEL_DIR, exist_ok=True)
    for filename, parts in MODELS.items():
        generate_obj(filename, parts)


if __name__ == "__main__":
    main()
