#!/usr/bin/env python3
"""Generate OBJ 3D mesh models for jumpdrive_tweaks bridge console and jump lever."""

import os
import math

MODEL_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)))


def rotate_x(vert, angle_rad, pivot_y, pivot_z):
    x, y, z = vert
    dy = y - pivot_y
    dz = z - pivot_z
    ny = pivot_y + dy * math.cos(angle_rad) - dz * math.sin(angle_rad)
    nz = pivot_z + dy * math.sin(angle_rad) + dz * math.cos(angle_rad)
    return (round(x, 4), round(ny, 4), round(nz, 4))


def generate_obj(filename, parts):
    lines = []
    lines.append("# Generated by generate_bridge_models.py for jumpdrive_tweaks")

    vertex_index = 1
    all_groups = []

    for mat_name, shapes in parts:
        faces_for_mat = []
        for shape in shapes:
            rot_angle = 0
            pivot_y = 0
            pivot_z = 0

            if len(shape) == 2 and shape[0] == "rot_x":
                # ("rot_x", (angle_deg, py, pz, box_shape))
                _, (deg, py, pz, box_shape) = shape
                rot_angle = math.radians(deg)
                pivot_y = py
                pivot_z = pz
                shape = box_shape

            if len(shape) == 6:
                x1, y1, z1, x2, y2, z2 = shape
                verts = [
                    (x1, y1, z1),
                    (x2, y1, z1),
                    (x2, y2, z1),
                    (x1, y2, z1),
                    (x1, y1, z2),
                    (x2, y1, z2),
                    (x2, y2, z2),
                    (x1, y2, z2),
                ]

                if rot_angle != 0:
                    verts = [rotate_x(v, rot_angle, pivot_y, pivot_z) for v in verts]

                for vx, vy, vz in verts:
                    lines.append(f"v {vx} {vy} {vz}")

                vi = vertex_index
                faces_for_mat.extend([
                    (vi + 0, vi + 1, vi + 2, vi + 3), # North / Front (Z1)
                    (vi + 5, vi + 4, vi + 7, vi + 6), # South / Back (Z2)
                    (vi + 4, vi + 0, vi + 3, vi + 7), # West / Left (X1)
                    (vi + 1, vi + 5, vi + 6, vi + 2), # East / Right (X2)
                    (vi + 3, vi + 2, vi + 6, vi + 7), # Top (Y2)
                    (vi + 4, vi + 5, vi + 1, vi + 0), # Bottom (Y1)
                ])
                vertex_index += 8
            elif len(shape) == 7 and shape[0] == "cyl_x":
                # Cylinder aligned along X axis: ("cyl_x", x1, x2, cy, cz, r, segs)
                _, x1, x2, cy, cz, r, segs = shape
                lines.append(f"v {x1} {cy} {cz}")
                lines.append(f"v {x2} {cy} {cz}")
                vi_left_center = vertex_index
                vi_right_center = vertex_index + 1
                vertex_index += 2

                start_vi = vertex_index
                for i in range(segs):
                    angle = 2 * math.pi * i / segs
                    vy = cy + r * math.cos(angle)
                    vz = cz + r * math.sin(angle)
                    lines.append(f"v {x1} {vy:.4f} {vz:.4f}")
                    lines.append(f"v {x2} {vy:.4f} {vz:.4f}")
                    vertex_index += 2

                for i in range(segs):
                    l1 = start_vi + i * 2
                    r1 = start_vi + i * 2 + 1
                    l2 = start_vi + ((i + 1) % segs) * 2
                    r2 = start_vi + ((i + 1) % segs) * 2 + 1

                    # Tube face
                    faces_for_mat.append((l1, r1, r2, l2))
                    # Left cap
                    faces_for_mat.append((l2, l1, vi_left_center, vi_left_center))
                    # Right cap
                    faces_for_mat.append((r1, r2, vi_right_center, vi_right_center))

        all_groups.append((mat_name, faces_for_mat))

    lines.append("vt 0 1")
    lines.append("vt 1 1")
    lines.append("vt 1 0")
    lines.append("vt 0 0")

    for mat_name, faces in all_groups:
        lines.append("")
        lines.append(f"usemtl {mat_name}")
        lines.append(f"g {mat_name.lower()}_group")
        for a, b, c, d in faces:
            lines.append(f"f {a}/1 {b}/2 {c}/3 {d}/4")

    lines.append("")

    filepath = os.path.join(MODEL_DIR, filename)
    with open(filepath, "w") as f:
        f.write("\n".join(lines))
    total_verts = (vertex_index - 1)
    total_faces = sum(len(g[1]) for g in all_groups)
    print(f"Generated {filename}: {total_verts} verts, {total_faces} faces")


MODELS = {
    # 1. BRIDGE NAVIGATION CONSOLE
    # Material 1: Hull metal casing (jumpdrive_bridge_console_side.png)
    # Material 2: Screen display (jumpdrive_bridge_console_top.png)
    # Material 3: Controls, keyboard, dial panels (jumpdrive_bridge_console_front.png)
    "jumpdrive_bridge_console.obj": [
        ("Mat1_Casing", [
            (-0.45, -0.50, -0.45,  0.45, -0.20,  0.45), # Base pedestal
            (-0.40, -0.20, -0.40,  0.40,  0.05,  0.40), # Main desk column
            (-0.48,  0.05, -0.45,  0.48,  0.14,  0.08), # Lower keyboard desk slab
            (-0.44,  0.08,  0.12,  0.44,  0.48,  0.44), # Back screen housing / bezel
            (-0.48,  0.08, -0.45, -0.42,  0.20,  0.08), # Left side guard
            ( 0.42,  0.08, -0.45,  0.48,  0.20,  0.08), # Right side guard
        ]),
        ("Mat2_Screen", [
            (-0.38,  0.14,  0.09,  0.38,  0.44,  0.13), # Radar & Navigation HUD (proud of back housing)
        ]),
        ("Mat3_Controls", [
            (-0.40,  0.14, -0.42,  0.40,  0.16,  0.05), # Keyboard matrix, throttle sliders, LED strip
        ]),
    ],

    # 2. HEAVY INDUSTRIAL JUMP LEVER (DISENGAGED / UPRIGHT STATE)
    # Material 1: Base bracket and hinge axle
    # Material 2: Lever handle and hazard grip
    "jumpdrive_jump_lever_off.obj": [
        ("Mat1_Bracket", [
            (-0.22, -0.32,  0.40,  0.22,  0.32,  0.50), # Backplate mount
            (-0.16, -0.12,  0.18, -0.08,  0.14,  0.40), # Left hinge bracket
            ( 0.08, -0.12,  0.18,  0.16,  0.14,  0.40), # Right hinge bracket
            ("cyl_x", -0.16, 0.16, 0.01, 0.28, 0.045, 8), # Center pivot pin
        ]),
        ("Mat2_Lever", [
            (-0.05, -0.04,  0.22,  0.05,  0.36,  0.32), # Heavy upright actuator arm
            (-0.10,  0.34,  0.18,  0.10,  0.45,  0.36), # Industrial T-handle hazard grip
        ]),
    ],

    # 3. HEAVY INDUSTRIAL JUMP LEVER (ENGAGED / PULLED FORWARD STATE)
    # Uses exact rigid rotation of -65 degrees around pivot axle (y=0.01, z=0.28)
    "jumpdrive_jump_lever_on.obj": [
        ("Mat1_Bracket", [
            (-0.22, -0.32,  0.40,  0.22,  0.32,  0.50), # Backplate mount
            (-0.16, -0.12,  0.18, -0.08,  0.14,  0.40), # Left hinge bracket
            ( 0.08, -0.12,  0.18,  0.16,  0.14,  0.40), # Right hinge bracket
            ("cyl_x", -0.16, 0.16, 0.01, 0.28, 0.045, 8), # Center pivot pin
        ]),
        ("Mat2_Lever", [
            ("rot_x", (-65, 0.01, 0.28, (-0.05, -0.04, 0.22, 0.05, 0.36, 0.32))), # Rotated actuator arm
            ("rot_x", (-65, 0.01, 0.28, (-0.10,  0.34, 0.18, 0.10, 0.45, 0.36))), # Rotated T-handle grip
        ]),
    ],
}


def main():
    os.makedirs(MODEL_DIR, exist_ok=True)
    for filename, parts in MODELS.items():
        generate_obj(filename, parts)


if __name__ == "__main__":
    main()
