name = bweapons_tweaks
description = Custom tweaks for bweapons modpack (Techage integration, durability fixes)
depends = bweapons_api, bweapons_firearms_pack, bweapons_hitech_pack, techage, basic_materials, tnt
optional_depends = bweapons_bows_pack, bweapons_magic_pack, bweapons_utility_pack, anvil, tnt_tweaks
